version: "3.8"
services:
  db:
    image: mongo:6
    container_name: hcshop_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db

  backend:
    build: ./backend
    container_name: hcshop_backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE=mongodb://db:27017/hcshop
      - PORT=3000
    volumes:
      - ./backend:/app
    command: npm start

  frontend:
    build: ./frontend
    container_name: hcshop_frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
